// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateChannelReleaseHandlerFunc turns a function with the right signature into a create channel release handler
type CreateChannelReleaseHandlerFunc func(CreateChannelReleaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateChannelReleaseHandlerFunc) Handle(params CreateChannelReleaseParams) middleware.Responder {
	return fn(params)
}

// CreateChannelReleaseHandler interface for that can handle valid create channel release params
type CreateChannelReleaseHandler interface {
	Handle(CreateChannelReleaseParams) middleware.Responder
}

// NewCreateChannelRelease creates a new http.Handler for the create channel release operation
func NewCreateChannelRelease(ctx *middleware.Context, handler CreateChannelReleaseHandler) *CreateChannelRelease {
	return &CreateChannelRelease{Context: ctx, Handler: handler}
}

/*CreateChannelRelease swagger:route POST /api/v1/packages/{namespace}/{package}/channels/{channel}/{release} channel createChannelRelease

Add a release to a channel

*/
type CreateChannelRelease struct {
	Context *middleware.Context
	Handler CreateChannelReleaseHandler
}

func (o *CreateChannelRelease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateChannelReleaseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
