// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteChannelReleaseHandlerFunc turns a function with the right signature into a delete channel release handler
type DeleteChannelReleaseHandlerFunc func(DeleteChannelReleaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteChannelReleaseHandlerFunc) Handle(params DeleteChannelReleaseParams) middleware.Responder {
	return fn(params)
}

// DeleteChannelReleaseHandler interface for that can handle valid delete channel release params
type DeleteChannelReleaseHandler interface {
	Handle(DeleteChannelReleaseParams) middleware.Responder
}

// NewDeleteChannelRelease creates a new http.Handler for the delete channel release operation
func NewDeleteChannelRelease(ctx *middleware.Context, handler DeleteChannelReleaseHandler) *DeleteChannelRelease {
	return &DeleteChannelRelease{Context: ctx, Handler: handler}
}

/*DeleteChannelRelease swagger:route DELETE /api/v1/packages/{namespace}/{package}/channels/{channel}/{release} channel deleteChannelRelease

Remove a release from the channel

*/
type DeleteChannelRelease struct {
	Context *middleware.Context
	Handler DeleteChannelReleaseHandler
}

func (o *DeleteChannelRelease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteChannelReleaseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
