// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bryanl/ksonnet-registry/models"
)

// DeleteChannelOKCode is the HTTP code returned for type DeleteChannelOK
const DeleteChannelOKCode int = 200

/*DeleteChannelOK successful operation

swagger:response deleteChannelOK
*/
type DeleteChannelOK struct {

	/*
	  In: Body
	*/
	Payload models.DeleteChannelOKBody `json:"body,omitempty"`
}

// NewDeleteChannelOK creates DeleteChannelOK with default headers values
func NewDeleteChannelOK() *DeleteChannelOK {
	return &DeleteChannelOK{}
}

// WithPayload adds the payload to the delete channel o k response
func (o *DeleteChannelOK) WithPayload(payload models.DeleteChannelOKBody) *DeleteChannelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete channel o k response
func (o *DeleteChannelOK) SetPayload(payload models.DeleteChannelOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChannelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeleteChannelOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeleteChannelUnauthorizedCode is the HTTP code returned for type DeleteChannelUnauthorized
const DeleteChannelUnauthorizedCode int = 401

/*DeleteChannelUnauthorized Not authorized to read the package

swagger:response deleteChannelUnauthorized
*/
type DeleteChannelUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteChannelUnauthorized creates DeleteChannelUnauthorized with default headers values
func NewDeleteChannelUnauthorized() *DeleteChannelUnauthorized {
	return &DeleteChannelUnauthorized{}
}

// WithPayload adds the payload to the delete channel unauthorized response
func (o *DeleteChannelUnauthorized) WithPayload(payload *models.Error) *DeleteChannelUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete channel unauthorized response
func (o *DeleteChannelUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChannelUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChannelNotFoundCode is the HTTP code returned for type DeleteChannelNotFound
const DeleteChannelNotFoundCode int = 404

/*DeleteChannelNotFound Package not found

swagger:response deleteChannelNotFound
*/
type DeleteChannelNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteChannelNotFound creates DeleteChannelNotFound with default headers values
func NewDeleteChannelNotFound() *DeleteChannelNotFound {
	return &DeleteChannelNotFound{}
}

// WithPayload adds the payload to the delete channel not found response
func (o *DeleteChannelNotFound) WithPayload(payload *models.Error) *DeleteChannelNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete channel not found response
func (o *DeleteChannelNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChannelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
