// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bryanl/ksonnet-registry/models"
)

// ListChannelsOKCode is the HTTP code returned for type ListChannelsOK
const ListChannelsOKCode int = 200

/*ListChannelsOK successful operation

swagger:response listChannelsOK
*/
type ListChannelsOK struct {

	/*
	  In: Body
	*/
	Payload models.ListChannelsOKBody `json:"body,omitempty"`
}

// NewListChannelsOK creates ListChannelsOK with default headers values
func NewListChannelsOK() *ListChannelsOK {
	return &ListChannelsOK{}
}

// WithPayload adds the payload to the list channels o k response
func (o *ListChannelsOK) WithPayload(payload models.ListChannelsOKBody) *ListChannelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list channels o k response
func (o *ListChannelsOK) SetPayload(payload models.ListChannelsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListChannelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.ListChannelsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ListChannelsUnauthorizedCode is the HTTP code returned for type ListChannelsUnauthorized
const ListChannelsUnauthorizedCode int = 401

/*ListChannelsUnauthorized Not authorized to read the package

swagger:response listChannelsUnauthorized
*/
type ListChannelsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListChannelsUnauthorized creates ListChannelsUnauthorized with default headers values
func NewListChannelsUnauthorized() *ListChannelsUnauthorized {
	return &ListChannelsUnauthorized{}
}

// WithPayload adds the payload to the list channels unauthorized response
func (o *ListChannelsUnauthorized) WithPayload(payload *models.Error) *ListChannelsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list channels unauthorized response
func (o *ListChannelsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListChannelsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListChannelsNotFoundCode is the HTTP code returned for type ListChannelsNotFound
const ListChannelsNotFoundCode int = 404

/*ListChannelsNotFound Package not found

swagger:response listChannelsNotFound
*/
type ListChannelsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListChannelsNotFound creates ListChannelsNotFound with default headers values
func NewListChannelsNotFound() *ListChannelsNotFound {
	return &ListChannelsNotFound{}
}

// WithPayload adds the payload to the list channels not found response
func (o *ListChannelsNotFound) WithPayload(payload *models.Error) *ListChannelsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list channels not found response
func (o *ListChannelsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListChannelsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
