// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListChannelsHandlerFunc turns a function with the right signature into a list channels handler
type ListChannelsHandlerFunc func(ListChannelsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListChannelsHandlerFunc) Handle(params ListChannelsParams) middleware.Responder {
	return fn(params)
}

// ListChannelsHandler interface for that can handle valid list channels params
type ListChannelsHandler interface {
	Handle(ListChannelsParams) middleware.Responder
}

// NewListChannels creates a new http.Handler for the list channels operation
func NewListChannels(ctx *middleware.Context, handler ListChannelsHandler) *ListChannels {
	return &ListChannels{Context: ctx, Handler: handler}
}

/*ListChannels swagger:route GET /api/v1/packages/{namespace}/{package}/channels channel listChannels

List channels

*/
type ListChannels struct {
	Context *middleware.Context
	Handler ListChannelsHandler
}

func (o *ListChannels) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListChannelsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
