// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bryanl/ksonnet-registry/models"
)

// ShowChannelOKCode is the HTTP code returned for type ShowChannelOK
const ShowChannelOKCode int = 200

/*ShowChannelOK successful operation

swagger:response showChannelOK
*/
type ShowChannelOK struct {

	/*
	  In: Body
	*/
	Payload models.ShowChannelOKBody `json:"body,omitempty"`
}

// NewShowChannelOK creates ShowChannelOK with default headers values
func NewShowChannelOK() *ShowChannelOK {
	return &ShowChannelOK{}
}

// WithPayload adds the payload to the show channel o k response
func (o *ShowChannelOK) WithPayload(payload models.ShowChannelOKBody) *ShowChannelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show channel o k response
func (o *ShowChannelOK) SetPayload(payload models.ShowChannelOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowChannelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.ShowChannelOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ShowChannelUnauthorizedCode is the HTTP code returned for type ShowChannelUnauthorized
const ShowChannelUnauthorizedCode int = 401

/*ShowChannelUnauthorized Not authorized to read the package

swagger:response showChannelUnauthorized
*/
type ShowChannelUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShowChannelUnauthorized creates ShowChannelUnauthorized with default headers values
func NewShowChannelUnauthorized() *ShowChannelUnauthorized {
	return &ShowChannelUnauthorized{}
}

// WithPayload adds the payload to the show channel unauthorized response
func (o *ShowChannelUnauthorized) WithPayload(payload *models.Error) *ShowChannelUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show channel unauthorized response
func (o *ShowChannelUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowChannelUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ShowChannelNotFoundCode is the HTTP code returned for type ShowChannelNotFound
const ShowChannelNotFoundCode int = 404

/*ShowChannelNotFound Package not found

swagger:response showChannelNotFound
*/
type ShowChannelNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShowChannelNotFound creates ShowChannelNotFound with default headers values
func NewShowChannelNotFound() *ShowChannelNotFound {
	return &ShowChannelNotFound{}
}

// WithPayload adds the payload to the show channel not found response
func (o *ShowChannelNotFound) WithPayload(payload *models.Error) *ShowChannelNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show channel not found response
func (o *ShowChannelNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowChannelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
