// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ShowChannelHandlerFunc turns a function with the right signature into a show channel handler
type ShowChannelHandlerFunc func(ShowChannelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShowChannelHandlerFunc) Handle(params ShowChannelParams) middleware.Responder {
	return fn(params)
}

// ShowChannelHandler interface for that can handle valid show channel params
type ShowChannelHandler interface {
	Handle(ShowChannelParams) middleware.Responder
}

// NewShowChannel creates a new http.Handler for the show channel operation
func NewShowChannel(ctx *middleware.Context, handler ShowChannelHandler) *ShowChannel {
	return &ShowChannel{Context: ctx, Handler: handler}
}

/*ShowChannel swagger:route GET /api/v1/packages/{namespace}/{package}/channels/{channel} channel showChannel

show channel

*/
type ShowChannel struct {
	Context *middleware.Context
	Handler ShowChannelHandler
}

func (o *ShowChannel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShowChannelParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
