// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePackageReleaseParams creates a new DeletePackageReleaseParams object
// with the default values initialized.
func NewDeletePackageReleaseParams() *DeletePackageReleaseParams {
	var ()
	return &DeletePackageReleaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePackageReleaseParamsWithTimeout creates a new DeletePackageReleaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePackageReleaseParamsWithTimeout(timeout time.Duration) *DeletePackageReleaseParams {
	var ()
	return &DeletePackageReleaseParams{

		timeout: timeout,
	}
}

// NewDeletePackageReleaseParamsWithContext creates a new DeletePackageReleaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePackageReleaseParamsWithContext(ctx context.Context) *DeletePackageReleaseParams {
	var ()
	return &DeletePackageReleaseParams{

		Context: ctx,
	}
}

// NewDeletePackageReleaseParamsWithHTTPClient creates a new DeletePackageReleaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePackageReleaseParamsWithHTTPClient(client *http.Client) *DeletePackageReleaseParams {
	var ()
	return &DeletePackageReleaseParams{
		HTTPClient: client,
	}
}

/*DeletePackageReleaseParams contains all the parameters to send to the API endpoint
for the delete package release operation typically these are written to a http.Request
*/
type DeletePackageReleaseParams struct {

	/*Namespace
	  namespace

	*/
	Namespace string
	/*Package
	  package name

	*/
	Package string
	/*Release
	  release name

	*/
	Release string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete package release params
func (o *DeletePackageReleaseParams) WithTimeout(timeout time.Duration) *DeletePackageReleaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete package release params
func (o *DeletePackageReleaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete package release params
func (o *DeletePackageReleaseParams) WithContext(ctx context.Context) *DeletePackageReleaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete package release params
func (o *DeletePackageReleaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete package release params
func (o *DeletePackageReleaseParams) WithHTTPClient(client *http.Client) *DeletePackageReleaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete package release params
func (o *DeletePackageReleaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the delete package release params
func (o *DeletePackageReleaseParams) WithNamespace(namespace string) *DeletePackageReleaseParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete package release params
func (o *DeletePackageReleaseParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPackage adds the packageVar to the delete package release params
func (o *DeletePackageReleaseParams) WithPackage(packageVar string) *DeletePackageReleaseParams {
	o.SetPackage(packageVar)
	return o
}

// SetPackage adds the package to the delete package release params
func (o *DeletePackageReleaseParams) SetPackage(packageVar string) {
	o.Package = packageVar
}

// WithRelease adds the release to the delete package release params
func (o *DeletePackageReleaseParams) WithRelease(release string) *DeletePackageReleaseParams {
	o.SetRelease(release)
	return o
}

// SetRelease adds the release to the delete package release params
func (o *DeletePackageReleaseParams) SetRelease(release string) {
	o.Release = release
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePackageReleaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param package
	if err := r.SetPathParam("package", o.Package); err != nil {
		return err
	}

	// path param release
	if err := r.SetPathParam("release", o.Release); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
