// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PullPackageJSONHandlerFunc turns a function with the right signature into a pull package Json handler
type PullPackageJSONHandlerFunc func(PullPackageJSONParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PullPackageJSONHandlerFunc) Handle(params PullPackageJSONParams) middleware.Responder {
	return fn(params)
}

// PullPackageJSONHandler interface for that can handle valid pull package Json params
type PullPackageJSONHandler interface {
	Handle(PullPackageJSONParams) middleware.Responder
}

// NewPullPackageJSON creates a new http.Handler for the pull package Json operation
func NewPullPackageJSON(ctx *middleware.Context, handler PullPackageJSONHandler) *PullPackageJSON {
	return &PullPackageJSON{Context: ctx, Handler: handler}
}

/*PullPackageJSON swagger:route GET /api/v1/packages/{namespace}/{package}/{release}/{media_type}/pull/json package blobs pullPackageJson

Download the package

*/
type PullPackageJSON struct {
	Context *middleware.Context
	Handler PullPackageJSONHandler
}

func (o *PullPackageJSON) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPullPackageJSONParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
