// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Ksonnet Registry API
Ksonnet Registry API documentation



    Schemes:
      http
    Host: localhost:5000
    BasePath: /
    Version: 0.1.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: bryan@heptio.com

    Consumes:
    - application/json

    Produces:
    - application/json
    - application/x-gzip

swagger:meta
*/
package restapi
