// Code generated by go-swagger; DO NOT EDIT.

package blobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bryanl/ksonnet-registry/models"
)

// PullBlobJSONOKCode is the HTTP code returned for type PullBlobJSONOK
const PullBlobJSONOKCode int = 200

/*PullBlobJSONOK successful operation

swagger:response pullBlobJsonOK
*/
type PullBlobJSONOK struct {

	/*
	  In: Body
	*/
	Payload *models.PullJSON `json:"body,omitempty"`
}

// NewPullBlobJSONOK creates PullBlobJSONOK with default headers values
func NewPullBlobJSONOK() *PullBlobJSONOK {
	return &PullBlobJSONOK{}
}

// WithPayload adds the payload to the pull blob Json o k response
func (o *PullBlobJSONOK) WithPayload(payload *models.PullJSON) *PullBlobJSONOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pull blob Json o k response
func (o *PullBlobJSONOK) SetPayload(payload *models.PullJSON) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PullBlobJSONOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PullBlobJSONUnauthorizedCode is the HTTP code returned for type PullBlobJSONUnauthorized
const PullBlobJSONUnauthorizedCode int = 401

/*PullBlobJSONUnauthorized Not authorized to read the package

swagger:response pullBlobJsonUnauthorized
*/
type PullBlobJSONUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPullBlobJSONUnauthorized creates PullBlobJSONUnauthorized with default headers values
func NewPullBlobJSONUnauthorized() *PullBlobJSONUnauthorized {
	return &PullBlobJSONUnauthorized{}
}

// WithPayload adds the payload to the pull blob Json unauthorized response
func (o *PullBlobJSONUnauthorized) WithPayload(payload *models.Error) *PullBlobJSONUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pull blob Json unauthorized response
func (o *PullBlobJSONUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PullBlobJSONUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PullBlobJSONNotFoundCode is the HTTP code returned for type PullBlobJSONNotFound
const PullBlobJSONNotFoundCode int = 404

/*PullBlobJSONNotFound Package not found

swagger:response pullBlobJsonNotFound
*/
type PullBlobJSONNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPullBlobJSONNotFound creates PullBlobJSONNotFound with default headers values
func NewPullBlobJSONNotFound() *PullBlobJSONNotFound {
	return &PullBlobJSONNotFound{}
}

// WithPayload adds the payload to the pull blob Json not found response
func (o *PullBlobJSONNotFound) WithPayload(payload *models.Error) *PullBlobJSONNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pull blob Json not found response
func (o *PullBlobJSONNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PullBlobJSONNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
