// Code generated by go-swagger; DO NOT EDIT.

package blobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bryanl/ksonnet-registry/models"
)

// PullBlobOKCode is the HTTP code returned for type PullBlobOK
const PullBlobOKCode int = 200

/*PullBlobOK successful operation

swagger:response pullBlobOK
*/
type PullBlobOK struct {

	/*
	  In: Body
	*/
	Payload models.PullBlobOKBody `json:"body,omitempty"`
}

// NewPullBlobOK creates PullBlobOK with default headers values
func NewPullBlobOK() *PullBlobOK {
	return &PullBlobOK{}
}

// WithPayload adds the payload to the pull blob o k response
func (o *PullBlobOK) WithPayload(payload models.PullBlobOKBody) *PullBlobOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pull blob o k response
func (o *PullBlobOK) SetPayload(payload models.PullBlobOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PullBlobOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// PullBlobUnauthorizedCode is the HTTP code returned for type PullBlobUnauthorized
const PullBlobUnauthorizedCode int = 401

/*PullBlobUnauthorized Not authorized to read the package

swagger:response pullBlobUnauthorized
*/
type PullBlobUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPullBlobUnauthorized creates PullBlobUnauthorized with default headers values
func NewPullBlobUnauthorized() *PullBlobUnauthorized {
	return &PullBlobUnauthorized{}
}

// WithPayload adds the payload to the pull blob unauthorized response
func (o *PullBlobUnauthorized) WithPayload(payload *models.Error) *PullBlobUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pull blob unauthorized response
func (o *PullBlobUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PullBlobUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PullBlobNotFoundCode is the HTTP code returned for type PullBlobNotFound
const PullBlobNotFoundCode int = 404

/*PullBlobNotFound Package not found

swagger:response pullBlobNotFound
*/
type PullBlobNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPullBlobNotFound creates PullBlobNotFound with default headers values
func NewPullBlobNotFound() *PullBlobNotFound {
	return &PullBlobNotFound{}
}

// WithPayload adds the payload to the pull blob not found response
func (o *PullBlobNotFound) WithPayload(payload *models.Error) *PullBlobNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pull blob not found response
func (o *PullBlobNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PullBlobNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
