// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bryanl/ksonnet-registry/models"
)

// DeletePackageReleaseNoContentCode is the HTTP code returned for type DeletePackageReleaseNoContent
const DeletePackageReleaseNoContentCode int = 204

/*DeletePackageReleaseNoContent successful operation

swagger:response deletePackageReleaseNoContent
*/
type DeletePackageReleaseNoContent struct {
}

// NewDeletePackageReleaseNoContent creates DeletePackageReleaseNoContent with default headers values
func NewDeletePackageReleaseNoContent() *DeletePackageReleaseNoContent {
	return &DeletePackageReleaseNoContent{}
}

// WriteResponse to the client
func (o *DeletePackageReleaseNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeletePackageReleaseUnauthorizedCode is the HTTP code returned for type DeletePackageReleaseUnauthorized
const DeletePackageReleaseUnauthorizedCode int = 401

/*DeletePackageReleaseUnauthorized Not authorized to read the package

swagger:response deletePackageReleaseUnauthorized
*/
type DeletePackageReleaseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePackageReleaseUnauthorized creates DeletePackageReleaseUnauthorized with default headers values
func NewDeletePackageReleaseUnauthorized() *DeletePackageReleaseUnauthorized {
	return &DeletePackageReleaseUnauthorized{}
}

// WithPayload adds the payload to the delete package release unauthorized response
func (o *DeletePackageReleaseUnauthorized) WithPayload(payload *models.Error) *DeletePackageReleaseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete package release unauthorized response
func (o *DeletePackageReleaseUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePackageReleaseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePackageReleaseNotFoundCode is the HTTP code returned for type DeletePackageReleaseNotFound
const DeletePackageReleaseNotFoundCode int = 404

/*DeletePackageReleaseNotFound Package not found

swagger:response deletePackageReleaseNotFound
*/
type DeletePackageReleaseNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePackageReleaseNotFound creates DeletePackageReleaseNotFound with default headers values
func NewDeletePackageReleaseNotFound() *DeletePackageReleaseNotFound {
	return &DeletePackageReleaseNotFound{}
}

// WithPayload adds the payload to the delete package release not found response
func (o *DeletePackageReleaseNotFound) WithPayload(payload *models.Error) *DeletePackageReleaseNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete package release not found response
func (o *DeletePackageReleaseNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePackageReleaseNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
