// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePackageReleaseHandlerFunc turns a function with the right signature into a delete package release handler
type DeletePackageReleaseHandlerFunc func(DeletePackageReleaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePackageReleaseHandlerFunc) Handle(params DeletePackageReleaseParams) middleware.Responder {
	return fn(params)
}

// DeletePackageReleaseHandler interface for that can handle valid delete package release params
type DeletePackageReleaseHandler interface {
	Handle(DeletePackageReleaseParams) middleware.Responder
}

// NewDeletePackageRelease creates a new http.Handler for the delete package release operation
func NewDeletePackageRelease(ctx *middleware.Context, handler DeletePackageReleaseHandler) *DeletePackageRelease {
	return &DeletePackageRelease{Context: ctx, Handler: handler}
}

/*DeletePackageRelease swagger:route DELETE /api/v1/packages/{namespace}/{package}/{release} package deletePackageRelease

Delete a package release

*/
type DeletePackageRelease struct {
	Context *middleware.Context
	Handler DeletePackageReleaseHandler
}

func (o *DeletePackageRelease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePackageReleaseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
