// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ShowPackageReleasesHandlerFunc turns a function with the right signature into a show package releases handler
type ShowPackageReleasesHandlerFunc func(ShowPackageReleasesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShowPackageReleasesHandlerFunc) Handle(params ShowPackageReleasesParams) middleware.Responder {
	return fn(params)
}

// ShowPackageReleasesHandler interface for that can handle valid show package releases params
type ShowPackageReleasesHandler interface {
	Handle(ShowPackageReleasesParams) middleware.Responder
}

// NewShowPackageReleases creates a new http.Handler for the show package releases operation
func NewShowPackageReleases(ctx *middleware.Context, handler ShowPackageReleasesHandler) *ShowPackageReleases {
	return &ShowPackageReleases{Context: ctx, Handler: handler}
}

/*ShowPackageReleases swagger:route GET /api/v1/packages/{namespace}/{package} package showPackageReleases

List all releases for a package

*/
type ShowPackageReleases struct {
	Context *middleware.Context
	Handler ShowPackageReleasesHandler
}

func (o *ShowPackageReleases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShowPackageReleasesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
