// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ShowPackageHandlerFunc turns a function with the right signature into a show package handler
type ShowPackageHandlerFunc func(ShowPackageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShowPackageHandlerFunc) Handle(params ShowPackageParams) middleware.Responder {
	return fn(params)
}

// ShowPackageHandler interface for that can handle valid show package params
type ShowPackageHandler interface {
	Handle(ShowPackageParams) middleware.Responder
}

// NewShowPackage creates a new http.Handler for the show package operation
func NewShowPackage(ctx *middleware.Context, handler ShowPackageHandler) *ShowPackage {
	return &ShowPackage{Context: ctx, Handler: handler}
}

/*ShowPackage swagger:route GET /api/v1/packages/{namespace}/{package}/{release}/{media_type} package showPackage

Show a package

*/
type ShowPackage struct {
	Context *middleware.Context
	Handler ShowPackageHandler
}

func (o *ShowPackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShowPackageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
