// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// ShowPackageURL generates an URL for the show package operation
type ShowPackageURL struct {
	MediaType string
	Namespace string
	Package   string
	Release   string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ShowPackageURL) WithBasePath(bp string) *ShowPackageURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ShowPackageURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ShowPackageURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/api/v1/packages/{namespace}/{package}/{release}/{media_type}"

	mediaType := o.MediaType
	if mediaType != "" {
		_path = strings.Replace(_path, "{media_type}", mediaType, -1)
	} else {
		return nil, errors.New("MediaType is required on ShowPackageURL")
	}
	namespace := o.Namespace
	if namespace != "" {
		_path = strings.Replace(_path, "{namespace}", namespace, -1)
	} else {
		return nil, errors.New("Namespace is required on ShowPackageURL")
	}
	packageVar := o.Package
	if packageVar != "" {
		_path = strings.Replace(_path, "{package}", packageVar, -1)
	} else {
		return nil, errors.New("Package is required on ShowPackageURL")
	}
	release := o.Release
	if release != "" {
		_path = strings.Replace(_path, "{release}", release, -1)
	} else {
		return nil, errors.New("Release is required on ShowPackageURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ShowPackageURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ShowPackageURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ShowPackageURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ShowPackageURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ShowPackageURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ShowPackageURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
