// Code generated by go-swagger; DO NOT EDIT.

package package_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ShowPackageReleaseHandlerFunc turns a function with the right signature into a show package release handler
type ShowPackageReleaseHandlerFunc func(ShowPackageReleaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShowPackageReleaseHandlerFunc) Handle(params ShowPackageReleaseParams) middleware.Responder {
	return fn(params)
}

// ShowPackageReleaseHandler interface for that can handle valid show package release params
type ShowPackageReleaseHandler interface {
	Handle(ShowPackageReleaseParams) middleware.Responder
}

// NewShowPackageRelease creates a new http.Handler for the show package release operation
func NewShowPackageRelease(ctx *middleware.Context, handler ShowPackageReleaseHandler) *ShowPackageRelease {
	return &ShowPackageRelease{Context: ctx, Handler: handler}
}

/*ShowPackageRelease swagger:route GET /api/v1/packages/{namespace}/{package}/{release} package showPackageRelease

show package release

show package release

*/
type ShowPackageRelease struct {
	Context *middleware.Context
	Handler ShowPackageReleaseHandler
}

func (o *ShowPackageRelease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShowPackageReleaseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
