// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/runtime"
)

// PullBlobOKBody package-targz
// swagger:model pullBlobOKBody
type PullBlobOKBody runtime.File

// Validate validates this pull blob o k body
func (m *PullBlobOKBody) Validate(formats strfmt.Registry) error {
	return nil
}
