// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/runtime"
)

// PullPackageOKBody package-targz
// swagger:model pullPackageOKBody
type PullPackageOKBody runtime.File

// Validate validates this pull package o k body
func (m *PullPackageOKBody) Validate(formats strfmt.Registry) error {
	return nil
}
